name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.4.0


  cupertino_icons: ^1.0.2

  permission_handler: ^10.2.0
  flutter_blue_elves: ^0.1.9
  logging: ^1.1.1
  hex: ^0.2.0
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
